import { tbcX } from "@/config/font";
import "@/styles/globals.css";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${tbcX.className} min-h-screen`}>
        <TRPCReactProvider>
          <header className="top-0 z-40 w-full border-b">
            <div className="container flex h-20 items-center justify-between space-x-4 sm:space-x-0">
              <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                logo
              </h1>
            </div>
          </header>
          {children}
          <footer className="bottom-0 z-40 w-full border-t text-xs">
            <div className="container flex flex-col gap-12 px-4 pb-8 pt-12 sm:px-11 lg:flex-row-reverse lg:items-center lg:justify-between lg:p-7">
              <p className="text-gray-900 dark:text-gray-100">
                © 2024 company. All rights reserved.
              </p>
            </div>
          </footer>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
